kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq1routetlss
  namespace: mq 
spec:
  host: tlss.chl.mq.ibm.com
  to:
    kind: Service
    name: mq1-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
