apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq1
  namespace: mq
spec:
  telemetry:
    tracing:
      instana:
        enabled: true
  securityContext:
    supplementalGroups: [65534] # Change to 99 for clusters with RHEL7 or earlier worker nodes
  license:
    accept: true
    #license: L-APIG-CAUEBE
    license: L-VTPK-22YZPK
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    imagePullPolicy: Always
    storage:
      defaultClass: ocs-storagecluster-cephfs
      queueManager:
        type: persistent-claim
    availability:
      updateStrategy: RollingUpdate
      #type: MultiInstance
      #type: SingleInstance
      type: NativeHA
    metrics:
      enabled: true
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 2Gi
    name: QM1CP4I1
    mqsc:
    - configMap:
        name: mq1-mqsc
        items:
        - ivt.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'no'
            - name: LOG_LEVEL
              value: 'debug'
          name: qmgr
        
  version: 9.3.5.0-r1
  web:
    enabled: true
  pki:
    keys:
      - name: label1
        secret:
          secretName: mq1key
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust1
        secret:
          secretName: tls-eris-trust
          items:
            - CSQ9.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
